### ISSUE TITLE
intervals could be represented more explicitly

### ISSUE THREAD

**Issue by davepacheco** [bendrucker/postgres-interval#1]
This is migrated from brianc/node-pg-types#15.

The code for parsing intervals explicitly removes properties having zero values.  This leads to some confusing cases.  Here's my test program "test.js":

``` javascript
var pg = require('pg');
var util = require('util');

var conString = 'postgres://localhost/zag';
var query = process.argv[2];

if (!query) {
        console.error('node test.js QUERY_STRING');
        process.exit(2);
}

pg.connect(conString, function (err, client, done) {
        if (err) {
                console.error('pg.connect: %s', err.message);
                process.exit(1);
        }

        client.query(query, function (err, result) {
                console.error(util.inspect(result, null, 5));
                done();
                process.exit(0);
        });
});
```

Here's a zero interval:

```
$ node test.js 'select NOW() - NOW() as my_interval'
{ command: 'SELECT',
  rowCount: 1,
  oid: NaN,
  rows: [ { my_interval: {} } ],
  fields: 
   [ { name: 'my_interval',
       tableID: 0,
       columnID: 0,
       dataTypeID: 1186,
       dataTypeSize: 16,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers: [ [Function] ],
  RowCtor: [Function],
  rowAsArray: false,
  _getTypeParser: [Function] }
```

It seems a little weird that "{}" denotes "0 seconds".

Here's an interval of 1 hour and 5 seconds, which is a little weird because "hours" and "seconds" are both present, but "minutes" isn't:

```
$ node test.js "select TIMESTAMP '2014-01-26T12:00:00Z' - TIMESTAMP '2014-01-26T10:59:55Z' as my_interval;"
{ command: 'SELECT',
  rowCount: 1,
  oid: NaN,
  rows: [ { my_interval: { hours: 1, seconds: 5 } } ],
  fields: 
   [ { name: 'my_interval',
       tableID: 0,
       columnID: 0,
       dataTypeID: 1186,
       dataTypeSize: 16,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers: [ [Function] ],
  RowCtor: [Function],
  rowAsArray: false,
  _getTypeParser: [Function] }
```

This is a little odd and makes it a little complicated to construct a human-readable string from this because you have to know all the properties that might exist and check for all of them.  I'm not sure what to suggest instead, though.  One reasonable option would be to represent intervals with only the total seconds (or milliseconds or nanoseconds) and assume the caller will use a library for working with them and formatting them.

**Comment by bendrucker** [comment]
I think it's reasonable to fill all properties with zeros that are not defined -- how about you?

**Comment by davepacheco** [comment]
That works as long as the set of possible properties is documented (and committed).  When I was writing code to convert this into human-readable intervals, I found myself wondering if I needed to check for properties like "year" or "years" or whatever.  The problem is that if someone misses one of these properties because they didn't know to look for it (possibly because they never worked with intervals larger than a few minutes or something), then their code can produce wildly incorrect results without knowing it.

For reference, here's what I ended up doing:
https://github.com/joyent/manatee/blob/master/bin/manatee-adm#L1323-L1365

**Comment by bendrucker** [comment]
Sure. 0 as a default it is. And I'll clarify the props on the interval instances

**Comment by elmigranto** [comment]
This also seems to affect non-integer values:

``` js
(new (require('pg').Pool)).query("select '0.5 seconds'::interval", console.log);
// [ anonymous { interval: PostgresInterval {} } ]

//└─┬ pg@6.0.2
//  └─┬ pg-types@1.11.0
//    └── postgres-interval@1.0.2
```

**Comment by ekifox** [comment]
UP
