### ISSUE TITLE
Cast Anonymous Object into a Postgres-Interval Object?

### ISSUE THREAD

**Issue by sirwesley** [bendrucker/postgres-interval#27]
Not necessarily a bug, but need a way to cast Anonymous Object into a Postgres-Interval Object.  

**Steps to reproduce**
I pull data out of the database...
01:23:23 => {hours: 1, minutes: 23, seconds: 23} Postgres-Interval Object;

Need way to take  Anonymous Object  {hours: 1, minutes: 23, seconds: 23} and convert to Postgres-Interval Object  {hours: 1, minutes: 23, seconds: 23}, so that I can use the function .toPostgres() on that object.  

If there was a constructor that could accept the anonymous object, I'd be off to the races.  

Currently, I'm having to convert that anonymous object manually to a string, so that I can use the constructor provided.  

**Current process/workaround** 

1.  Data in database as Interval: 01:23:23 
2.  Parse data, get Postgres-Interval Object: {hours: 1, minutes: 23, seconds: 23}
3.  Backend->Frontend->Backend (object type lost: Postgres-Interval Object=> Anonymous Object)
4.  Format the object from Anonymous Object to HH:MM:SS  
5.  var interval = parse(HH:MM:SS)
6.  interval.toPostgres() => "1 hour 23 minutes 23 seconds"

Need constructor that accepts the identical output of step 2 so that I can get the Anonymous Object into a Postgres-Interval Object.  Seems like I should be able to skip steps 4 & 5 (converting twice).  

Open to suggestions on how to convert/cast Anonymous Object into a Postgres-Interval Object.  Appreciate any help.

**Comment by bendrucker** [comment]
Does this work for you?

```js
const obj = { seconds : 10 }
Interval.prototype.toPostgres.call(obj)
```
