### ISSUE TITLE
Version 0.0.1?

### ISSUE THREAD

**Issue by tomhughes** [bendrucker/postgres-interval#3]
Did you mean to release a version 0.0.1 that was lower numbered than the previous 1.0.0 release? or was it meant to be 1.0.1?

**Comment by bendrucker** [comment]
well the original was 0.0.0 by accident, so that bit's correct. releasing 1.0 now.

**Comment by bendrucker** [comment]
done

**Comment by tomhughes** [comment]
I was going by https://github.com/bendrucker/postgres-interval/releases which listed 1.0.0 and 0.0.1 and the fact that pg-types wanted 1.0.0 at least.

Thanks for the quick update anyway ;-)
