### ISSUE TITLE
Simplifying ISO duration format

### ISSUE THREAD

**Issue by odub** [bendrucker/postgres-interval#30]
Hi,

For ease of reading, I've written short helper function that shortens ISO 8601 duration strings to their minimal form eg. `P0Y0M0DT0H9M0S` to `PT9M`.

Would anyone else find this useful? I'm happy to contribute it with tests if so.

Open to suggestions about APIs, the ones that come to mind are:
1) `PostgresInterval#toISOString({ simplify: true });`
2) `PostgresInterval#toISOString({ short: true });`
3) `PostgresInterval#toISOStringShort();`

Thanks for your work on this lib! Cheers!

**Comment by bendrucker** [comment]
Happy to take that! Since `toISOString()` mirrors the method on `Date.prototype`, `toISOStringShort` or similar sounds good.
