### ISSUE TITLE
[Question]: changes in new version

### ISSUE THREAD

**Issue by tmtron** [bendrucker/postgres-interval#32]
is there some kind of change-log?

I wonder what has changed in version 2.x

**Comment by bendrucker** [comment]
There is no distinct change log, see the commit history, which includes version bumps:

https://github.com/bendrucker/postgres-interval/commits/master

**Comment by tmtron** [comment]
thanks. For others that come here, [here](https://github.com/bendrucker/postgres-interval/commit/02ce627713d0b21178f20559b6831d6a19a06cc4) is a breaking change in 2.0  
`IPostgresInterval` members are now required and initialized to `0`
