### ISSUE TITLE
Is a slight refactor welcome?

### ISSUE THREAD

**Issue by benjie** [bendrucker/postgres-interval#33]
Hey @bendrucker, thanks for your work on this project!

I've [re-implemented the parse function in PostGraphile](https://github.com/graphile/graphile-engine/blob/fix-types-tests/packages/graphile-build-pg/src/postgresInterval.js), with the following changes (roughly):

- Uses `(?:...)` [in the wrapper-regexps](https://github.com/graphile/graphile-engine/blob/690bf06cb2dbcc0bb37a99d765f7497978f733b4/packages/graphile-build-pg/src/postgresInterval.js#L20) to reduce the number of capture groups
- [Destructures from the matches](https://github.com/graphile/graphile-engine/blob/690bf06cb2dbcc0bb37a99d765f7497978f733b4/packages/graphile-build-pg/src/postgresInterval.js#L55-L64) in a straightforward way
- Changes the seconds/milliseconds to be [captured as one group](https://github.com/graphile/graphile-engine/blob/690bf06cb2dbcc0bb37a99d765f7497978f733b4/packages/graphile-build-pg/src/postgresInterval.js#L15): `(\\d\\d(?:\\.\\d{1,6})?)`
- [Pins the regexp](https://github.com/graphile/graphile-engine/blob/690bf06cb2dbcc0bb37a99d765f7497978f733b4/packages/graphile-build-pg/src/postgresInterval.js#L18-L21) with `^...$` to ensure it matches the whole string
- [Returns a zero-interval](https://github.com/graphile/graphile-engine/blob/690bf06cb2dbcc0bb37a99d765f7497978f733b4/packages/graphile-build-pg/src/postgresInterval.js#L47) rather than `{}` if `!interval`. (Maybe this should return `null` instead?)
- Removes the `parseMilliseconds` function as it's no-longer necessary
- Removes the `reduce` loop, instead using [unrolled simple assignment](https://github.com/graphile/graphile-engine/blob/690bf06cb2dbcc0bb37a99d765f7497978f733b4/packages/graphile-build-pg/src/postgresInterval.js#L68-L74)

Would you like me to replicate these changes in a PR to `postgres-interval`? I'm pretty confident I can do it in a non-breaking way (it won't be a complete copy of the above code because I'll need to add `milliseconds` back in, at least).

The result of this change would be:

- slightly better performance
- slightly reduced memory usage
- more linear code

If this is not of interest; feel free to close this issue :+1:

**Comment by bendrucker** [comment]
Yes, this sounds good! This code is pretty old. Would like to see some benchmarks around any perf oriented changes but certainly anything you think improves readability is more than welcome.
