### ISSUE TITLE
interval.toPostgres() format

### ISSUE THREAD

**Issue by aboqasem** [bendrucker/postgres-interval#38]
Hi @bendrucker!

Thank you for this cool package! Is it intentional that `interval.toPostgres()` returns the string ordered from seconds to years instead of years to seconds?

[Postgres docs](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES):

```
1 year 2 months 3 days 4 hours 5 minutes 6 seconds
```

This package:

```
6 seconds 5 minutes 4 hours 3 days 2 months 1 years
```

Notice the `s` in years as well.

If it is not intentional, may I contribute to fix it? If it is, feel free to close this issue.

Thanks!

**Comment by bendrucker** [comment]
Hmm, originally written way too long ago to say whether it was intentional, but generally the goal of these libraries is to match the PG implementation. PR welcome to change it, will be a new major.
