### ISSUE TITLE
Optional fields in `IPostgresInterval`

### ISSUE THREAD

**Issue by c4854469c7f86af43b58246fb1782** [bendrucker/postgres-interval#46]
Hi Ben.
I am Dante from Japan. how's weather like over there? 🏞

Attached below is `index.d.ts` v4.0.0.
https://github.com/bendrucker/postgres-interval/blob/338bfe94f0585f7f05349fd26bfbe759042d8d2a/index.d.ts#L2-L9

I have a  question on `IPostgresInterval`.

When a column (::`PostgresInterval`) has its value of  `0 years 3 mons 0 days 0 hours 0 mins 0.0 secs`, all fields but `mons` gets `undefined` which is arguable because their type is number.

Hope your brilliant thoughts.

**Comment by bendrucker** [comment]
Can you provide a failing test? There's already a passing test indicating that values should be zero even if the interval is entirely empty:

https://github.com/bendrucker/postgres-interval/blob/338bfe94f0585f7f05349fd26bfbe759042d8d2a/test.js#L42-L52

**Comment by c4854469c7f86af43b58246fb1782** [comment]
here's my env.
```javascript
// node version
16.15.0
// npm version
npm : 8.5.5
// package.json 
"postgres-interval": "^4.0.0",
// postgres version
postgres : postgres:13-alpine
```

test code(L43) gives an object like below.
```javascript
PostgresInterval {
  years: 0,
  months: 0,
  days: 0,
  hours: 0,
  minutes: 0,
  seconds: 0,
  milliseconds: 0
}
```
which is different from what it is initialized in postgres.

I have a `PostgresInterval` column named usable_period. 
![Screen Shot 2022-07-05 at 10 22 04](https://user-images.githubusercontent.com/55175301/177231527-ecf4bc42-4013-42e6-937f-9527d4d0c40f.png)

And it gives object like below when I query it with `"pg": "^8.7.1",`
```javascript
PostgresInterval { years: 1 }
```

**Comment by bendrucker** [comment]
Proper way to set a version for a transitive dependency is using `overrides`:

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

Seems pretty certain you're not actually using the version you think you've installed.

**Comment by bendrucker** [comment]
Doesn't seem like there's an issue with this package. If you `require` the package and call `setTypeParser` to register it that will work. Or setting `overrides` in the package will work. But simply installing another version has no effect, as Node will make sure both versions `3` and `4` are installed to meet the differing requirements. `pg-types` will get `3` as it requests in its package, while `4` will go unused unless you `require` it.

At some point we'll definitely bump these packages in `pg-types` but there's a tradeoff of added noise if we do that on every major revision to a single type. The separate packages are designed to give users the flexibility to upgrade specific types ahead of their eventual release as defaults.
