### ISSUE TITLE
Leading zeroes ignored in parsing of milliseconds

### ISSUE THREAD

**Issue by dvorakroth** [bendrucker/postgres-interval#49]
# The Problem

When parsing a time that includes an amount of milliseconds under 100, the parse function erroneously ignores the leading zeroes.

# Steps to reproduce

```javascript
const PostgresInterval = require('postgres-interval');

console.log(PostgresInterval('04:20:00.069').milliseconds); // should print 69, instead prints 690
```

**Comment by charmander** [comment]
i am not surprised this was hiding in #48

**Comment by bendrucker** [comment]
Haven't had a chance to fix this yet but happy to review a fix ASAP from anyone who wants to contribute one.
