### ISSUE TITLE
Incomplete parsing for some inputs

### ISSUE THREAD

**Issue by Wenzil** [bendrucker/postgres-interval#6]
``` js
const parse = require('postgres-interval');

parse('4 years 1 month 1 day 23:05:59:750');
// { years: 4, months: 1 }

parse('1 month 1 day 23:05:59:750');
// { months: 1 }

parse('1 year 1 day 23:05:59:750')
// correct
```

**Comment by Wenzil** [comment]
Using version 1.0.2

**Comment by Wenzil** [comment]
Also

``` js
parse('0 month 1 day 23:05:59:750')
// {}

parse('1 year 1 day 23:05:59:750')
// correct
```

**Comment by Wenzil** [comment]
Basically looks like it stops parsing after months

**Comment by Wenzil** [comment]
Also

``` js
parse('1 year 2 days 23:05:59:750')
// correct

parse('2 days 1 year 23:05:59:750')
// { days: 2 }
```

The order of (years, days) changes the result, but both orders are valid in SQL.

**Comment by elmigranto** [comment]
> both orders are valid in SQL

This module isn't supposed to parse "valid SQL", it converts Postgres interval output from string into JS object (and back). It looks like the only supported `intervalstyle` is `postgres`, which uses:
- `year months days time` order;
- `mon` or `mons` for months part.

Convert your string to `4 years 1 mons 1 days 23:05:59:750` and it should work (well, [not quite](https://github.com/bendrucker/postgres-interval/pull/8)).

For more info, see [Interval Input](https://www.postgresql.org/docs/current/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES) and [Interval Output](https://www.postgresql.org/docs/current/static/datatype-datetime.html#DATATYPE-INTERVAL-OUTPUT) in the docs.

That being said, there are definetly some issues with RegExp approach, but it mostly works fine, if you use values obtained directly from database.

**Comment by bendrucker** [comment]
Can I get some clarification on the sources of those intervals? Are they actual pg output?

**Comment by bendrucker** [comment]
Hi there, closing this based on lack of activity. If this is still a problem feel free to add more info as requested and I can reopen.
