### ISSUE TITLE
Invalid RegExp for time

### ISSUE THREAD

**Issue by elmigranto** [bendrucker/postgres-interval#7]
I've [noticed](https://github.com/bendrucker/postgres-interval/issues/1#issuecomment-232906694) `postgres-interval` doesn't parse fractions on time value, even though [docs state](https://www.postgresql.org/docs/current/static/datatype-datetime.html):

> `time`, `timestamp`, and `interval` accept an optional precision value `p` which specifies the number of fractional digits retained in the seconds field. By default, there is no explicit bound on precision. The allowed range of `p` is from 0 to 6 for the `timestamp` and `interval` types.

<sup>This is true as far as [8.0](https://www.postgresql.org/docs/8.0/static/datatype-datetime.html).</sup>

Looks like invalid regexp to me — `:` used as a separator, but `.` is the correct one. There are couple of related issues I'll try to fix. PR is coming…

**Comment by bendrucker** [comment]
Is this resolved by #8?

**Comment by elmigranto** [comment]
> Is this resolved by #8?

Yes.

Except in #8 I have `milliseconds`, but I think a better approach would be to have fractional part on `seconds` field and remove `milliseconds` entirely. This would also be closer to they way PG outputs intervals. I made those changes in my fork, if you have time to look through:

https://github.com/elmigranto/postgres-interval/tree/v2

**Comment by bendrucker** [comment]
Can you send a PR?

**Comment by elmigranto** [comment]
From my `v2`?

**Comment by bendrucker** [comment]
Sure

**Comment by bendrucker** [comment]
Seems like this was mostly resolved by #8. If there's anything remaining here happy to continue reviewing PRs.
